name: actions Workflow

on:
  push:
    branches:
      - main
  #repository_dispatch:
  schedule:
    - cron: "0/2 * * * *"
    - cron: "0/5 * * * *"

  pull_request:
    branches:
      - main
      # - 'feature/*' #matches feature/feat1, feature/feat2 and it doesn’t match feature/feat3/test, To match this we use double * 
      # - 'feature/**'
      # - '!feature/feat4' #ignore this matching brach 
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JavaS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Aman
      - name: Log Greetting Time
        run: echo "${{steps.greet.outputs.time}}"
